### ISSUE TITLE
const http requires some more http

### ISSUE THREAD

**Issue by Gingeropolous** [ShenNoether/MiniNodo#3]
root@monkey-desktop:/monerodo/MiniNodo# node MiniNodo.js

/monerodo/MiniNodo/node_modules/monero-nodejs/lib/wallet.js:2
const http = require('http');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/monerodo/MiniNodo/MiniNodo.js:11:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
root@monkey-desktop:/monerodo/MiniNodo#

**Comment by ShenNoether** [comment]
@Gingeropolous What OS are you using (it works fine here) regardless, on the last commit I replaced the use of const in that lib with var so I would guess it solves that. Please comment if not.

**Comment by ShenNoether** [comment]
Also, this is probably an issue for https://github.com/PsychicCat/monero-nodejs I would guess.
